// Generated by scripts/prepare-portfolio-previews.mjs. Public derivatives only.
export interface ImagePreviewAsset { image: string; width: number; height: number }
export const imagePreviewAssets: Readonly<Record<string, ImagePreviewAsset>> = {
  "one-to-z:20-11372": {
    "image": "/assets/previews/one-to-z-20-11372-preview.webp",
    "width": 390,
    "height": 1254
  },
  "one-to-z:20-11483": {
    "image": "/assets/previews/one-to-z-20-11483-preview.webp",
    "width": 390,
    "height": 1522
  },
  "one-to-z:20-11622": {
    "image": "/assets/previews/one-to-z-20-11622-preview.webp",
    "width": 390,
    "height": 1259
  },
  "one-to-z:20-11694": {
    "image": "/assets/previews/one-to-z-20-11694-preview.webp",
    "width": 390,
    "height": 1393
  },
  "one-to-z:20-11774": {
    "image": "/assets/previews/one-to-z-20-11774-preview.webp",
    "width": 390,
    "height": 1042
  },
  "one-to-z:20-11859": {
    "image": "/assets/previews/one-to-z-20-11859-preview.webp",
    "width": 762,
    "height": 2400
  },
  "one-to-z:20-12142": {
    "image": "/assets/previews/one-to-z-20-12142-preview.webp",
    "width": 659,
    "height": 2400
  },
  "one-to-z:31-13532": {
    "image": "/assets/previews/one-to-z-31-13532-preview.webp",
    "width": 390,
    "height": 1042
  },
  "one-to-z:31-13648": {
    "image": "/assets/previews/one-to-z-31-13648-preview.webp",
    "width": 390,
    "height": 1537
  },
  "one-to-z:31-13795": {
    "image": "/assets/previews/one-to-z-31-13795-preview.webp",
    "width": 390,
    "height": 1443
  },
  "one-to-z:31-13922": {
    "image": "/assets/previews/one-to-z-31-13922-preview.webp",
    "width": 390,
    "height": 1867
  },
  "one-to-z:31-14020": {
    "image": "/assets/previews/one-to-z-31-14020-preview.webp",
    "width": 390,
    "height": 1817
  },
  "one-to-z:31-14147": {
    "image": "/assets/previews/one-to-z-31-14147-preview.webp",
    "width": 390,
    "height": 1375
  },
  "one-to-z:31-14226": {
    "image": "/assets/previews/one-to-z-31-14226-preview.webp",
    "width": 390,
    "height": 1364
  },
  "one-to-z:31-14363": {
    "image": "/assets/previews/one-to-z-31-14363-preview.webp",
    "width": 390,
    "height": 2108
  },
  "one-to-z:31-14515": {
    "image": "/assets/previews/one-to-z-31-14515-preview.webp",
    "width": 1200,
    "height": 1862
  },
  "one-to-z:31-14780": {
    "image": "/assets/previews/one-to-z-31-14780-preview.webp",
    "width": 748,
    "height": 2400
  },
  "one-to-z:31-15105": {
    "image": "/assets/previews/one-to-z-31-15105-preview.webp",
    "width": 526,
    "height": 2400
  },
  "designgraphy:about": {
    "image": "/assets/previews/designgraphy-about-preview.webp",
    "width": 1200,
    "height": 1132
  },
  "designgraphy:domestic": {
    "image": "/assets/previews/designgraphy-domestic-preview.webp",
    "width": 1200,
    "height": 1135
  },
  "designgraphy:global-universities": {
    "image": "/assets/previews/designgraphy-global-universities-preview.webp",
    "width": 1200,
    "height": 1133
  },
  "designgraphy:google": {
    "image": "/assets/previews/designgraphy-google-preview.webp",
    "width": 1200,
    "height": 652
  },
  "designgraphy:guides": {
    "image": "/assets/previews/designgraphy-guides-preview.webp",
    "width": 1200,
    "height": 1135
  },
  "designgraphy:home": {
    "image": "/assets/previews/designgraphy-home-preview.webp",
    "width": 1200,
    "height": 1206
  },
  "designgraphy:palette-soon": {
    "image": "/assets/previews/designgraphy-palette-soon-preview.webp",
    "width": 1200,
    "height": 652
  },
  "designgraphy:search-empty": {
    "image": "/assets/previews/designgraphy-search-empty-preview.webp",
    "width": 1200,
    "height": 652
  },
  "designgraphy:search": {
    "image": "/assets/previews/designgraphy-search-preview.webp",
    "width": 1200,
    "height": 652
  },
  "designgraphy:snu": {
    "image": "/assets/previews/designgraphy-snu-preview.webp",
    "width": 1200,
    "height": 652
  },
  "designgraphy:toss": {
    "image": "/assets/previews/designgraphy-toss-preview.webp",
    "width": 1200,
    "height": 837
  },
  "designgraphy:typography-soon": {
    "image": "/assets/previews/designgraphy-typography-soon-preview.webp",
    "width": 1200,
    "height": 652
  },
  "evidence:design-pick": {
    "image": "/assets/previews/evidence-design-pick-color-2026-10-10-preview.webp",
    "width": 1200,
    "height": 603
  },
  "evidence:naratmalsami": {
    "image": "/assets/previews/evidence-naratmalsami-typing-2026-10-10-preview.webp",
    "width": 1200,
    "height": 603
  },
  "evidence:planor": {
    "image": "/assets/previews/evidence-planor-calendar-2026-10-10-preview.webp",
    "width": 1200,
    "height": 603
  }
};
